In [2]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [3]:
net = simpleNet()
print(net.W)

x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)
np.argmax(p)

t = np.array([0, 0, 1])
net.loss(x, t)

[[-0.61781909 -0.51704719  0.10706269]
 [ 0.45419575  0.55417892  0.11173527]]
[0.03808472 0.18853272 0.16479935]


1.0664338850240456

In [4]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.18195885  0.21150075 -0.3934596 ]
 [ 0.27293827  0.31725113 -0.5901894 ]]


In [6]:
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)